version: '3.3'
services:
  node-server:
    container_name: guidking.api
    build: .
    command: 'sh -c "npm install && npm start"'
    image: node:11.5-alpine
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
    tty: true
    restart: always
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.1.7
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
