apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # - host: guidking.api
  #   http:
  #     paths:
  #     - path: /api
  #       backend:
  #         serviceName: guidking-api-service
  #         servicePort: 3000
  # - host: guidking.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: guidking-com-service
          servicePort: 80
  # - host: api.guidking.com
  #   http:
  #     paths:
  #     - path: /api
  #       backend:
  #         serviceName: guidking-api-service
  #         servicePort: 3000
